// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  f103Sidebar: [{ type: 'autogenerated', dirName: 'DShanMCU-F103' }],
  simulatorSidebar: [{ type: 'autogenerated', dirName: 'rtos-simulator' }],
};

export default sidebars;