import type { SidebarConfig } from '@vuepress/theme-default'

export const sidebarZh: SidebarConfig = {
  '/zh/FreeRTOS/DShanMCU-F103/': [
    {
      text: 'FreeRTOS入门与工程实践',
      collapsible: true,
      children: [
        '/zh/FreeRTOS/DShanMCU-F103/README.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter1.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter2.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter3.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter4.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter5.md', 
        '/zh/FreeRTOS/DShanMCU-F103/chapter6.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter7.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter8.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter9.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter10.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter11.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter12.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter13.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter14.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter15.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter16.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter17.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter18.md',
        '/zh/FreeRTOS/DShanMCU-F103/chapter19.md',
      ],
    },
  ],
  '/zh/FreeRTOS/simulator/': [
    {
      text: 'FreeRTOS快速入门',
      collapsible: true,
      children: [
        '/zh/FreeRTOS/simulator/README.md',
        '/zh/FreeRTOS/simulator/chapter1.md',
        '/zh/FreeRTOS/simulator/chapter2.md',
        '/zh/FreeRTOS/simulator/chapter3.md',
        '/zh/FreeRTOS/simulator/chapter4.md',
        '/zh/FreeRTOS/simulator/chapter5.md', 
        '/zh/FreeRTOS/simulator/chapter6.md',
        '/zh/FreeRTOS/simulator/chapter7.md',
        '/zh/FreeRTOS/simulator/chapter8.md',
        '/zh/FreeRTOS/simulator/chapter9.md',
        '/zh/FreeRTOS/simulator/chapter10.md',
        '/zh/FreeRTOS/simulator/chapter11.md',
        '/zh/FreeRTOS/simulator/chapter12.md',
        '/zh/FreeRTOS/simulator/chapter13.md',
        '/zh/FreeRTOS/simulator/chapter14.md',
      ],
    },
  ],
}
